/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/nav`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias/actividades` | `/materias/actividades`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias/detalleActividad` | `/materias/detalleActividad`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias/DetallePracticaAlumno` | `/materias/DetallePracticaAlumno`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias` | `/materias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/auth/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sessionService`; params?: Router.UnknownInputParams; } | { pathname: `/auth/tokenUtils`; params?: Router.UnknownInputParams; } | { pathname: `/auth/useAuth`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/nav`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/materias/actividades` | `/materias/actividades`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/materias/detalleActividad` | `/materias/detalleActividad`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/materias/DetallePracticaAlumno` | `/materias/DetallePracticaAlumno`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/materias` | `/materias`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sessionService`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/tokenUtils`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/useAuth`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/nav${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/materias/actividades${`?${string}` | `#${string}` | ''}` | `/materias/actividades${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/materias/detalleActividad${`?${string}` | `#${string}` | ''}` | `/materias/detalleActividad${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/materias/DetallePracticaAlumno${`?${string}` | `#${string}` | ''}` | `/materias/DetallePracticaAlumno${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/materias${`?${string}` | `#${string}` | ''}` | `/materias${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `/auth/AuthContext${`?${string}` | `#${string}` | ''}` | `/auth/sessionService${`?${string}` | `#${string}` | ''}` | `/auth/tokenUtils${`?${string}` | `#${string}` | ''}` | `/auth/useAuth${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/nav`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias/actividades` | `/materias/actividades`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias/detalleActividad` | `/materias/detalleActividad`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias/DetallePracticaAlumno` | `/materias/DetallePracticaAlumno`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/materias` | `/materias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/auth/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sessionService`; params?: Router.UnknownInputParams; } | { pathname: `/auth/tokenUtils`; params?: Router.UnknownInputParams; } | { pathname: `/auth/useAuth`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
